-- RORC App MVP schema
-- Sources:
-- 1) AppSheet Inspect round 1
-- 2) AppSheet Inspect round 2 MVP findings
-- 3) Current Membership, TimeSheet, and Heater Use spreadsheet structure
--
-- Scope for this first app build:
-- - Shared accounts / household memberships
-- - Individual account members
-- - Sign in / sign out
-- - Heater use
-- - Group heater pay
--
-- Deferred intentionally:
-- - Contracts
-- - Banners
-- - Projects/materials/steps
-- - Tutorials
-- - Window inventory/orders
-- - Messaging/notifications

create extension if not exists "pgcrypto";
create extension if not exists "citext";

do $$
begin
  if not exists (select 1 from pg_type where typname = 'membership_account_type') then
    create type public.membership_account_type as enum (
      'Active Membership',
      'Open Gym Only',
      'Billed Monthly',
      'Account Manager',
      'Account Past Due NO ACCESS ALLOWED'
    );
  end if;

  if not exists (select 1 from pg_type where typname = 'timesheet_kind') then
    create type public.timesheet_kind as enum ('Member', 'Guest');
  end if;

  if not exists (select 1 from pg_type where typname = 'timesheet_pass') then
    create type public.timesheet_pass as enum ('Day Pass', 'Open Gym');
  end if;

  if not exists (select 1 from pg_type where typname = 'heater_event') then
    create type public.heater_event as enum (
      'RORC',
      'KBYD',
      'MEMBER USE',
      'OPEN GYM',
      'RENTAL (All Day Or Hourly Rentals)'
    );
  end if;

  if not exists (select 1 from pg_type where typname = 'heater_state') then
    create type public.heater_state as enum ('On', 'Off');
  end if;

  if not exists (select 1 from pg_type where typname = 'account_billing_status') then
    create type public.account_billing_status as enum (
      'none',
      'incomplete',
      'trialing',
      'active',
      'past_due',
      'canceled',
      'unpaid',
      'paused'
    );
  end if;

  if not exists (select 1 from pg_type where typname = 'signup_status') then
    create type public.signup_status as enum (
      'submitted',
      'awaiting_payment',
      'active',
      'rejected',
      'canceled'
    );
  end if;

  if not exists (select 1 from pg_type where typname = 'automation_job_kind') then
    create type public.automation_job_kind as enum (
      'voice_monkey_sign_in',
      'voice_monkey_sign_out',
      'voice_monkey_after_hours',
      'heater_on',
      'heater_off',
      'closing_reminder',
      'admin_sms',
      'billing_sync'
    );
  end if;

  if not exists (select 1 from pg_type where typname = 'automation_job_status') then
    create type public.automation_job_status as enum (
      'pending',
      'processing',
      'completed',
      'failed',
      'canceled'
    );
  end if;
end $$;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- Raw import table from the AppSheet/Google Sheet membership source.
-- This remains the staging table; the app reads the normalized tables below.
create table if not exists public.current_memberships (
  id bigint generated by default as identity not null,
  source_row_number integer not null,
  member_name text null,
  legacy_password text null,
  account_type text null,
  account_number text null,
  membership_details text null,
  notes_on_account text null,
  expiration_date text null,
  billing_id_heater text null,
  marks_against_account text null,
  phone_number text null,
  email_address text null,
  image_path text null,
  stripe_customer_id text null,
  stripe_subscription_id text null,
  stripe_status text null,
  current_period_end text null,
  last_sync text null,
  imported_at timestamptz not null default now(),
  constraint current_memberships_pkey primary key (id),
  constraint current_memberships_source_row_number_key unique (source_row_number)
);

create index if not exists current_memberships_account_number_idx
  on public.current_memberships (account_number);

create index if not exists current_memberships_email_address_idx
  on public.current_memberships (email_address);

create index if not exists current_memberships_stripe_customer_id_idx
  on public.current_memberships (stripe_customer_id);

alter table public.current_memberships enable row level security;

create table if not exists public.accounts (
  id uuid primary key default gen_random_uuid(),
  account_number text not null unique,
  membership_details text,
  notes_on_account text,
  expiration_date date,
  billing_id_heater text,
  marks_against_account text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_accounts_account_number
  on public.accounts (account_number);

drop trigger if exists trg_accounts_updated_at on public.accounts;
create trigger trg_accounts_updated_at
before update on public.accounts
for each row
execute function public.set_updated_at();

create table if not exists public.account_members (
  id uuid primary key default gen_random_uuid(),
  account_id uuid not null references public.accounts(id) on delete restrict,
  member_name text not null,
  account_type public.membership_account_type not null default 'Active Membership',
  phone_number text,
  email_address citext,
  image_path text,
  allow_guest_entry boolean not null default false,
  is_billing_owner boolean not null default false,
  auth_user_id uuid references auth.users(id) on delete set null,
  legacy_source_row_number integer unique,
  legacy_member_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint account_members_member_name_not_blank check (btrim(member_name) <> '')
);

create index if not exists idx_account_members_account_id
  on public.account_members (account_id);

create index if not exists idx_account_members_email_address
  on public.account_members (email_address);

create index if not exists idx_account_members_account_type
  on public.account_members (account_type);

create unique index if not exists idx_account_members_auth_user_id_unique
  on public.account_members (auth_user_id)
  where auth_user_id is not null;

create unique index if not exists idx_account_members_account_member_name_unique
  on public.account_members (account_id, member_name);

create unique index if not exists idx_account_members_one_billing_owner
  on public.account_members (account_id)
  where is_billing_owner = true;

drop trigger if exists trg_account_members_updated_at on public.account_members;
create trigger trg_account_members_updated_at
before update on public.account_members
for each row
execute function public.set_updated_at();

create table if not exists public.account_type_permissions (
  account_type public.membership_account_type primary key,
  can_sign_in boolean not null default false,
  can_use_heater boolean not null default false,
  can_bring_guests boolean not null default false,
  can_manage_members boolean not null default false,
  bypass_time_windows boolean not null default false,
  allowed_days smallint[] not null default '{}',
  allowed_start_time time,
  allowed_end_time time,
  notes text,
  updated_at timestamptz not null default now()
);

insert into public.account_type_permissions (
  account_type,
  can_sign_in,
  can_use_heater,
  can_bring_guests,
  can_manage_members,
  bypass_time_windows,
  allowed_days,
  allowed_start_time,
  allowed_end_time,
  notes
) values
  ('Active Membership', true, true, false, false, false, array[0,1,2,3,4,5,6]::smallint[], time '06:50', time '21:10', 'Member access safety window for nominal 7am-9pm hours.'),
  ('Open Gym Only', true, false, false, false, false, array[2,4]::smallint[], time '17:50', time '20:10', 'Open Gym Only access on Tuesdays and Thursdays from 6pm-8pm, with a 10-minute safety window.'),
  ('Billed Monthly', true, true, false, false, false, array[0,1,2,3,4,5,6]::smallint[], time '06:50', time '21:10', 'Billed monthly access safety window for nominal 7am-9pm hours.'),
  ('Account Manager', true, true, true, true, true, '{}'::smallint[], null, null, 'Admin role with unrestricted access.'),
  ('Account Past Due NO ACCESS ALLOWED', false, false, false, false, false, '{}'::smallint[], null, null, 'Past-due account with no access.')
on conflict (account_type) do update set
  can_sign_in = excluded.can_sign_in,
  can_use_heater = excluded.can_use_heater,
  can_bring_guests = excluded.can_bring_guests,
  can_manage_members = excluded.can_manage_members,
  bypass_time_windows = excluded.bypass_time_windows,
  allowed_days = excluded.allowed_days,
  allowed_start_time = excluded.allowed_start_time,
  allowed_end_time = excluded.allowed_end_time,
  notes = excluded.notes,
  updated_at = now();

drop trigger if exists trg_account_type_permissions_updated_at on public.account_type_permissions;
create trigger trg_account_type_permissions_updated_at
before update on public.account_type_permissions
for each row
execute function public.set_updated_at();

create table if not exists public.member_credentials (
  account_member_id uuid primary key references public.account_members(id) on delete cascade,
  pin_hash text,
  must_reset_pin boolean not null default true,
  updated_at timestamptz not null default now()
);

drop trigger if exists trg_member_credentials_updated_at on public.member_credentials;
create trigger trg_member_credentials_updated_at
before update on public.member_credentials
for each row
execute function public.set_updated_at();

create table if not exists public.account_billing (
  account_id uuid primary key references public.accounts(id) on delete cascade,
  stripe_customer_id text,
  stripe_subscription_id text,
  stripe_status text,
  billing_status public.account_billing_status not null default 'none',
  current_period_end timestamptz,
  last_sync timestamptz,
  updated_at timestamptz not null default now()
);

create index if not exists idx_account_billing_stripe_customer_id
  on public.account_billing (stripe_customer_id);

create index if not exists idx_account_billing_stripe_subscription_id
  on public.account_billing (stripe_subscription_id);

drop trigger if exists trg_account_billing_updated_at on public.account_billing;
create trigger trg_account_billing_updated_at
before update on public.account_billing
for each row
execute function public.set_updated_at();

create table if not exists public.signup_contracts (
  id uuid primary key default gen_random_uuid(),
  account_id uuid references public.accounts(id) on delete set null,
  primary_member_id uuid references public.account_members(id) on delete set null,
  requested_account_number text,
  applicant_name text not null,
  applicant_email citext,
  applicant_phone text,
  requested_account_type public.membership_account_type not null default 'Active Membership',
  contract_payload jsonb not null default '{}'::jsonb,
  contract_signed_at timestamptz,
  stripe_checkout_session_id text,
  signup_status public.signup_status not null default 'submitted',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_signup_contracts_signup_status
  on public.signup_contracts (signup_status, created_at desc);

create index if not exists idx_signup_contracts_account_id
  on public.signup_contracts (account_id);

drop trigger if exists trg_signup_contracts_updated_at on public.signup_contracts;
create trigger trg_signup_contracts_updated_at
before update on public.signup_contracts
for each row
execute function public.set_updated_at();

create table if not exists public.timesheet_entries (
  id uuid primary key default gen_random_uuid(),
  log_id text not null unique default gen_random_uuid()::text,
  member_or_guest public.timesheet_kind not null,
  member_id uuid references public.account_members(id) on delete set null,
  guest_name text,
  day_pass_or_open_gym public.timesheet_pass,
  member_entered_with_id uuid references public.account_members(id) on delete set null,
  liability_accepted boolean not null default false,
  signed_in_at timestamptz not null default now(),
  signed_out_at timestamptz,
  additional_guests text[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint timesheet_member_requires_member_id check (
    member_or_guest <> 'Member' or member_id is not null
  ),
  constraint timesheet_guest_requires_guest_details check (
    member_or_guest <> 'Guest'
    or (
      guest_name is not null
      and btrim(guest_name) <> ''
      and member_entered_with_id is not null
      and liability_accepted = true
    )
  ),
  constraint timesheet_sign_out_after_sign_in check (
    signed_out_at is null or signed_out_at >= signed_in_at
  )
);

create index if not exists idx_timesheet_entries_member_id
  on public.timesheet_entries (member_id);

create index if not exists idx_timesheet_entries_member_entered_with_id
  on public.timesheet_entries (member_entered_with_id);

create index if not exists idx_timesheet_entries_signed_in_at
  on public.timesheet_entries (signed_in_at desc);

create index if not exists idx_timesheet_entries_currently_signed_in
  on public.timesheet_entries (signed_in_at desc)
  where signed_out_at is null;

drop trigger if exists trg_timesheet_entries_updated_at on public.timesheet_entries;
create trigger trg_timesheet_entries_updated_at
before update on public.timesheet_entries
for each row
execute function public.set_updated_at();

create table if not exists public.heater_use_entries (
  id uuid primary key default gen_random_uuid(),
  used_on date not null default current_date,
  event public.heater_event,
  responsible_member_id uuid references public.account_members(id) on delete set null,
  group_pay boolean not null default false,
  turn_heater_on public.heater_state not null default 'On',
  start_at timestamptz,
  end_at timestamptz,
  paid boolean not null default false,
  set_a_timer boolean not null default false,
  timer_start time,
  timer_stop time,
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint heater_non_group_requires_responsible_member check (
    group_pay = true or responsible_member_id is not null
  ),
  constraint heater_end_after_start check (
    start_at is null or end_at is null or end_at >= start_at
  )
);

create index if not exists idx_heater_use_entries_used_on
  on public.heater_use_entries (used_on desc);

create index if not exists idx_heater_use_entries_responsible_member_id
  on public.heater_use_entries (responsible_member_id);

drop trigger if exists trg_heater_use_entries_updated_at on public.heater_use_entries;
create trigger trg_heater_use_entries_updated_at
before update on public.heater_use_entries
for each row
execute function public.set_updated_at();

create table if not exists public.heater_use_group_members (
  heater_use_entry_id uuid not null references public.heater_use_entries(id) on delete cascade,
  account_member_id uuid not null references public.account_members(id) on delete restrict,
  added_at timestamptz not null default now(),
  primary key (heater_use_entry_id, account_member_id)
);

create index if not exists idx_heater_use_group_members_account_member_id
  on public.heater_use_group_members (account_member_id);

create table if not exists public.admin_alerts (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  alert_kind text not null,
  account_member_id uuid references public.account_members(id) on delete set null,
  context jsonb not null default '{}'::jsonb,
  resolved_at timestamptz
);

create index if not exists idx_admin_alerts_created_at
  on public.admin_alerts (created_at desc);

create index if not exists idx_admin_alerts_unresolved
  on public.admin_alerts (created_at desc)
  where resolved_at is null;

create table if not exists public.billing_line_items (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  account_member_id uuid not null references public.account_members(id) on delete restrict,
  timesheet_entry_id uuid references public.timesheet_entries(id) on delete set null,
  heater_use_entry_id uuid references public.heater_use_entries(id) on delete set null,
  amount_cents integer not null check (amount_cents >= 0),
  reason text not null,
  posted_to_stripe_at timestamptz
);

create index if not exists idx_billing_line_items_account_member_id
  on public.billing_line_items (account_member_id, created_at desc);

create index if not exists idx_billing_line_items_timesheet_entry_id
  on public.billing_line_items (timesheet_entry_id);

create index if not exists idx_billing_line_items_heater_use_entry_id
  on public.billing_line_items (heater_use_entry_id);

create unique index if not exists idx_billing_line_items_guest_fee_unique
  on public.billing_line_items (timesheet_entry_id, account_member_id)
  where timesheet_entry_id is not null;

create unique index if not exists idx_billing_line_items_heater_fee_unique
  on public.billing_line_items (heater_use_entry_id, account_member_id)
  where heater_use_entry_id is not null;

create table if not exists public.automation_jobs (
  id uuid primary key default gen_random_uuid(),
  kind public.automation_job_kind not null,
  job_status public.automation_job_status not null default 'pending',
  run_after timestamptz not null default now(),
  payload jsonb not null default '{}'::jsonb,
  attempts integer not null default 0 check (attempts >= 0),
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_automation_jobs_pending
  on public.automation_jobs (run_after, created_at)
  where job_status = 'pending';

create index if not exists idx_automation_jobs_kind
  on public.automation_jobs (kind, created_at desc);

drop trigger if exists trg_automation_jobs_updated_at on public.automation_jobs;
create trigger trg_automation_jobs_updated_at
before update on public.automation_jobs
for each row
execute function public.set_updated_at();

create or replace view public.timesheet_entries_with_duration
with (security_invoker = true) as
select
  te.*,
  case
    when te.signed_out_at is null then null
    else extract(epoch from (te.signed_out_at - te.signed_in_at)) / 60
  end as total_minutes
from public.timesheet_entries te;

create or replace view public.currently_signed_in
with (security_invoker = true) as
select *
from public.timesheet_entries
where signed_out_at is null;

create or replace view public.heater_use_entries_with_duration
with (security_invoker = true) as
select
  hue.*,
  case
    when hue.start_at is null or hue.end_at is null then null
    else extract(epoch from (hue.end_at - hue.start_at)) / 3600
  end as run_hours
from public.heater_use_entries hue;

create or replace function public.current_account_member_id()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select id
  from public.account_members
  where auth_user_id = auth.uid()
  limit 1;
$$;

create or replace function public.current_account_id()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select account_id
  from public.account_members
  where auth_user_id = auth.uid()
  limit 1;
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    exists (
      select 1
      from public.account_members
      where auth_user_id = auth.uid()
        and account_type = 'Account Manager'
    ),
    false
  );
$$;

create or replace function public.can_read_heater_use_entry(
  heater_entry_id uuid,
  responsible_member uuid
)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    public.current_account_member_id() is not null,
    false
  );
$$;

create or replace function public.can_read_heater_group_member(
  heater_entry_id uuid,
  group_account_member uuid
)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    public.current_account_member_id() is not null,
    false
  );
$$;

create or replace function public.account_billing_allows_access(
  account uuid,
  member_type public.membership_account_type
)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select case
    when member_type = 'Account Manager' then true
    else coalesce(
      (
        select billing_status in ('none', 'trialing', 'active')
        from public.account_billing
        where account_id = account
      ),
      true
    )
  end;
$$;

create or replace function public.member_has_access(member uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (
      select atp.can_sign_in
      from public.account_members am
      join public.account_type_permissions atp on atp.account_type = am.account_type
      where am.id = member
        and public.account_billing_allows_access(am.account_id, am.account_type)
    ),
    false
  );
$$;

create or replace function public.member_can_use_heater(member uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (
      select atp.can_use_heater
      from public.account_members am
      join public.account_type_permissions atp on atp.account_type = am.account_type
      where am.id = member
        and public.account_billing_allows_access(am.account_id, am.account_type)
    ),
    false
  );
$$;

create or replace function public.member_can_bring_guests(member uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (
      select atp.can_bring_guests or am.allow_guest_entry
      from public.account_members am
      join public.account_type_permissions atp on atp.account_type = am.account_type
      where am.id = member
        and public.account_billing_allows_access(am.account_id, am.account_type)
    ),
    false
  );
$$;

create or replace function public.is_sign_in_authorized(
  member uuid,
  signed_in_time timestamptz default now()
)
returns boolean
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  rule record;
  local_signed_in timestamp;
  local_day smallint;
  local_time time;
begin
  if member is null then
    return false;
  end if;

  select atp.*
  into rule
  from public.account_members am
  join public.account_type_permissions atp on atp.account_type = am.account_type
  where am.id = member
    and public.account_billing_allows_access(am.account_id, am.account_type);

  if not found or rule.can_sign_in = false then
    return false;
  end if;

  if rule.bypass_time_windows then
    return true;
  end if;

  local_signed_in := signed_in_time at time zone 'America/Los_Angeles';
  local_day := extract(dow from local_signed_in)::smallint;
  local_time := local_signed_in::time;

  if cardinality(rule.allowed_days) > 0 and not (local_day = any(rule.allowed_days)) then
    return false;
  end if;

  if rule.allowed_start_time is not null and rule.allowed_end_time is not null then
    if rule.allowed_start_time <= rule.allowed_end_time then
      return local_time >= rule.allowed_start_time and local_time <= rule.allowed_end_time;
    end if;

    return local_time >= rule.allowed_start_time or local_time <= rule.allowed_end_time;
  end if;

  return true;
end;
$$;

create or replace function public.protect_account_member_update()
returns trigger
language plpgsql
as $$
begin
  if auth.uid() is null or public.is_admin() then
    return new;
  end if;

  if old.auth_user_id is distinct from auth.uid() then
    raise exception 'Only the linked member can update this account member row.';
  end if;

  if (to_jsonb(new) - 'phone_number' - 'email_address' - 'image_path' - 'updated_at')
     is distinct from
     (to_jsonb(old) - 'phone_number' - 'email_address' - 'image_path' - 'updated_at') then
    raise exception 'Members can only update their own contact fields.';
  end if;

  return new;
end;
$$;

drop trigger if exists trg_protect_account_member_update on public.account_members;
create trigger trg_protect_account_member_update
before update on public.account_members
for each row
execute function public.protect_account_member_update();

create or replace function public.protect_timesheet_update()
returns trigger
language plpgsql
as $$
begin
  if old.signed_out_at is not null
     and new.signed_out_at is not null
     and old.signed_out_at <> new.signed_out_at then
    raise exception 'Cannot overwrite an existing sign-out time on timesheet row %.', old.id;
  end if;

  if auth.uid() is null or public.is_admin() then
    return new;
  end if;

  if (to_jsonb(new) - 'signed_out_at' - 'updated_at')
     is distinct from
     (to_jsonb(old) - 'signed_out_at' - 'updated_at') then
    raise exception 'Members can only update sign-out time.';
  end if;

  return new;
end;
$$;

drop trigger if exists trg_protect_timesheet_update on public.timesheet_entries;
create trigger trg_protect_timesheet_update
before update on public.timesheet_entries
for each row
execute function public.protect_timesheet_update();

create or replace function public.protect_heater_use_update()
returns trigger
language plpgsql
as $$
begin
  if old.end_at is not null
     and new.end_at is not null
     and old.end_at <> new.end_at then
    raise exception 'Cannot overwrite an existing heater end time on heater use row %.', old.id;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_protect_heater_use_update on public.heater_use_entries;
create trigger trg_protect_heater_use_update
before update on public.heater_use_entries
for each row
execute function public.protect_heater_use_update();

create or replace function public.auto_sign_out_open_rows(sign_out_time timestamptz default now())
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  affected integer;
begin
  update public.timesheet_entries
  set signed_out_at = sign_out_time
  where signed_out_at is null;

  get diagnostics affected = row_count;
  return affected;
end;
$$;

create or replace function public.alert_unauthorized_sign_in()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.member_or_guest = 'Member'
     and not public.is_sign_in_authorized(new.member_id, new.signed_in_at) then
    insert into public.admin_alerts (alert_kind, account_member_id, context)
    values (
      'unauthorized_sign_in',
      new.member_id,
      jsonb_build_object(
        'timesheet_entry_id', new.id,
        'signed_in_at', new.signed_in_at
      )
    );
  elsif new.member_or_guest = 'Guest'
        and not (
          public.is_sign_in_authorized(new.member_entered_with_id, new.signed_in_at)
          and public.member_can_bring_guests(new.member_entered_with_id)
        ) then
    insert into public.admin_alerts (alert_kind, account_member_id, context)
    values (
      'unauthorized_guest_sign_in',
      new.member_entered_with_id,
      jsonb_build_object(
        'timesheet_entry_id', new.id,
        'guest_name', new.guest_name,
        'signed_in_at', new.signed_in_at
      )
    );
  end if;

  return new;
end;
$$;

drop trigger if exists trg_alert_unauthorized_sign_in on public.timesheet_entries;
create trigger trg_alert_unauthorized_sign_in
after insert on public.timesheet_entries
for each row
execute function public.alert_unauthorized_sign_in();

create or replace function public.bill_guest_entry()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  guest_count integer;
begin
  if new.member_or_guest <> 'Guest'
     or new.member_entered_with_id is null
     or new.day_pass_or_open_gym <> 'Day Pass' then
    return new;
  end if;

  guest_count := 1 + coalesce(array_length(new.additional_guests, 1), 0);

  insert into public.billing_line_items (
    account_member_id,
    timesheet_entry_id,
    amount_cents,
    reason
  ) values (
    new.member_entered_with_id,
    new.id,
    guest_count * 25,
    'Guest entry fee for ' || guest_count || ' guest(s)'
  )
  on conflict do nothing;

  return new;
end;
$$;

drop trigger if exists trg_bill_guest_entry on public.timesheet_entries;
create trigger trg_bill_guest_entry
after insert on public.timesheet_entries
for each row
execute function public.bill_guest_entry();

create or replace function public.enqueue_timesheet_insert_automation()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  job_kind public.automation_job_kind;
begin
  if new.member_or_guest = 'Member'
     and public.is_sign_in_authorized(new.member_id, new.signed_in_at) then
    job_kind := 'voice_monkey_sign_in';
  elsif new.member_or_guest = 'Guest'
        and public.is_sign_in_authorized(new.member_entered_with_id, new.signed_in_at)
        and public.member_can_bring_guests(new.member_entered_with_id) then
    job_kind := 'voice_monkey_sign_in';
  else
    job_kind := 'admin_sms';
  end if;

  insert into public.automation_jobs (kind, payload)
  values (
    job_kind,
    jsonb_build_object(
      'timesheet_entry_id', new.id,
      'member_or_guest', new.member_or_guest,
      'member_id', new.member_id,
      'guest_name', new.guest_name,
      'member_entered_with_id', new.member_entered_with_id,
      'signed_in_at', new.signed_in_at
    )
  );

  return new;
end;
$$;

drop trigger if exists trg_enqueue_timesheet_insert_automation on public.timesheet_entries;
create trigger trg_enqueue_timesheet_insert_automation
after insert on public.timesheet_entries
for each row
execute function public.enqueue_timesheet_insert_automation();

create or replace function public.enqueue_timesheet_sign_out_automation()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if old.signed_out_at is null
     and new.signed_out_at is not null
     and not exists (
       select 1
       from public.timesheet_entries
       where signed_out_at is null
     ) then
    insert into public.automation_jobs (kind, payload)
    values (
      'voice_monkey_sign_out',
      jsonb_build_object(
        'last_timesheet_entry_id', new.id,
        'signed_out_at', new.signed_out_at
      )
    );
  end if;

  return new;
end;
$$;

drop trigger if exists trg_enqueue_timesheet_sign_out_automation on public.timesheet_entries;
create trigger trg_enqueue_timesheet_sign_out_automation
after update of signed_out_at on public.timesheet_entries
for each row
execute function public.enqueue_timesheet_sign_out_automation();

create or replace function public.enqueue_heater_automation()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.automation_jobs (kind, payload)
    values (
      'heater_on',
      jsonb_build_object(
        'heater_use_entry_id', new.id,
        'responsible_member_id', new.responsible_member_id,
        'group_pay', new.group_pay,
        'start_at', new.start_at,
        'event', new.event
      )
    );
  elsif tg_op = 'UPDATE'
        and old.end_at is null
        and new.end_at is not null then
    insert into public.automation_jobs (kind, payload)
    values (
      'heater_off',
      jsonb_build_object(
        'heater_use_entry_id', new.id,
        'responsible_member_id', new.responsible_member_id,
        'group_pay', new.group_pay,
        'start_at', new.start_at,
        'end_at', new.end_at,
        'event', new.event
      )
    );
  end if;

  return new;
end;
$$;

drop trigger if exists trg_enqueue_heater_insert_automation on public.heater_use_entries;
create trigger trg_enqueue_heater_insert_automation
after insert on public.heater_use_entries
for each row
execute function public.enqueue_heater_automation();

drop trigger if exists trg_enqueue_heater_end_automation on public.heater_use_entries;
create trigger trg_enqueue_heater_end_automation
after update of end_at on public.heater_use_entries
for each row
execute function public.enqueue_heater_automation();

create or replace function public.bill_heater_use_entry()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  total_cents integer;
  participant_count integer;
  base_cents integer;
  extra_cents integer;
  participant record;
begin
  if new.start_at is null or new.end_at is null then
    return new;
  end if;

  total_cents := greatest(
    0,
    ceiling((extract(epoch from (new.end_at - new.start_at)) / 3600.0) * 1300)::integer
  );

  if total_cents = 0 then
    return new;
  end if;

  if new.group_pay then
    select count(*)
    into participant_count
    from public.heater_use_group_members
    where heater_use_entry_id = new.id;

    if participant_count = 0 then
      insert into public.admin_alerts (alert_kind, account_member_id, context)
      values (
        'heater_group_pay_without_members',
        new.responsible_member_id,
        jsonb_build_object('heater_use_entry_id', new.id)
      );
      return new;
    end if;

    base_cents := total_cents / participant_count;
    extra_cents := total_cents % participant_count;

    for participant in
      select
        account_member_id,
        row_number() over (order by added_at, account_member_id) as participant_index
      from public.heater_use_group_members
      where heater_use_entry_id = new.id
    loop
      insert into public.billing_line_items (
        account_member_id,
        heater_use_entry_id,
        amount_cents,
        reason
      ) values (
        participant.account_member_id,
        new.id,
        base_cents + case when participant.participant_index <= extra_cents then 1 else 0 end,
        'Heater use group share'
      )
      on conflict do nothing;
    end loop;
  elsif new.responsible_member_id is not null then
    insert into public.billing_line_items (
      account_member_id,
      heater_use_entry_id,
      amount_cents,
      reason
    ) values (
      new.responsible_member_id,
      new.id,
      total_cents,
      'Heater use'
    )
    on conflict do nothing;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_bill_heater_use_entry on public.heater_use_entries;
create trigger trg_bill_heater_use_entry
after update of end_at on public.heater_use_entries
for each row
when (old.end_at is null and new.end_at is not null)
execute function public.bill_heater_use_entry();

alter table public.accounts enable row level security;
alter table public.account_members enable row level security;
alter table public.account_type_permissions enable row level security;
alter table public.member_credentials enable row level security;
alter table public.account_billing enable row level security;
alter table public.signup_contracts enable row level security;
alter table public.timesheet_entries enable row level security;
alter table public.heater_use_entries enable row level security;
alter table public.heater_use_group_members enable row level security;
alter table public.admin_alerts enable row level security;
alter table public.billing_line_items enable row level security;
alter table public.automation_jobs enable row level security;

drop policy if exists accounts_member_read on public.accounts;
create policy accounts_member_read on public.accounts
for select using (
  id = public.current_account_id()
  or public.is_admin()
);

drop policy if exists accounts_admin_write on public.accounts;
create policy accounts_admin_write on public.accounts
for all using (public.is_admin())
with check (public.is_admin());

drop policy if exists account_type_permissions_member_read on public.account_type_permissions;
create policy account_type_permissions_member_read on public.account_type_permissions
for select using (auth.uid() is not null);

drop policy if exists account_type_permissions_admin_write on public.account_type_permissions;
create policy account_type_permissions_admin_write on public.account_type_permissions
for all using (public.is_admin())
with check (public.is_admin());

drop policy if exists account_members_member_read on public.account_members;
create policy account_members_member_read on public.account_members
for select using (
  auth_user_id = auth.uid()
  or account_id = public.current_account_id()
  or public.is_admin()
);

drop policy if exists account_members_self_update on public.account_members;
create policy account_members_self_update on public.account_members
for update using (auth_user_id = auth.uid())
with check (auth_user_id = auth.uid());

drop policy if exists account_members_admin_write on public.account_members;
create policy account_members_admin_write on public.account_members
for all using (public.is_admin())
with check (public.is_admin());

drop policy if exists member_credentials_admin_only on public.member_credentials;
create policy member_credentials_admin_only on public.member_credentials
for all using (public.is_admin())
with check (public.is_admin());

drop policy if exists account_billing_owner_read on public.account_billing;
create policy account_billing_owner_read on public.account_billing
for select using (
  exists (
    select 1
    from public.account_members am
    where am.account_id = account_billing.account_id
      and am.auth_user_id = auth.uid()
      and am.is_billing_owner = true
  )
  or public.is_admin()
);

drop policy if exists account_billing_admin_only on public.account_billing;
create policy account_billing_admin_only on public.account_billing
for all using (public.is_admin())
with check (public.is_admin());

drop policy if exists signup_contracts_admin_only on public.signup_contracts;
create policy signup_contracts_admin_only on public.signup_contracts
for all using (public.is_admin())
with check (public.is_admin());

drop policy if exists timesheet_entries_member_read on public.timesheet_entries;
create policy timesheet_entries_member_read on public.timesheet_entries
for select using (
  member_id = public.current_account_member_id()
  or exists (
    select 1
    from public.account_members am
    where am.id = timesheet_entries.member_id
      and am.account_id = public.current_account_id()
  )
  or member_entered_with_id = public.current_account_member_id()
  or exists (
    select 1
    from public.account_members am
    where am.id = timesheet_entries.member_entered_with_id
      and am.account_id = public.current_account_id()
  )
  or public.is_admin()
);

drop policy if exists timesheet_entries_member_insert on public.timesheet_entries;
create policy timesheet_entries_member_insert on public.timesheet_entries
for insert with check (
  public.is_admin()
  or (
    member_or_guest = 'Member'
    and exists (
      select 1
      from public.account_members am
      where am.id = member_id
        and am.account_id = public.current_account_id()
    )
    and public.is_sign_in_authorized(member_id, signed_in_at)
  )
  or (
    member_or_guest = 'Guest'
    and member_entered_with_id = public.current_account_member_id()
    and public.is_sign_in_authorized(member_entered_with_id, signed_in_at)
    and public.member_can_bring_guests(member_entered_with_id)
    and liability_accepted = true
  )
);

drop policy if exists timesheet_entries_member_sign_out on public.timesheet_entries;
create policy timesheet_entries_member_sign_out on public.timesheet_entries
for update using (
  member_id = public.current_account_member_id()
  or exists (
    select 1
    from public.account_members am
    where am.id = timesheet_entries.member_id
      and am.account_id = public.current_account_id()
  )
  or member_entered_with_id = public.current_account_member_id()
  or exists (
    select 1
    from public.account_members am
    where am.id = timesheet_entries.member_entered_with_id
      and am.account_id = public.current_account_id()
  )
  or public.is_admin()
);

drop policy if exists timesheet_entries_admin_delete on public.timesheet_entries;
create policy timesheet_entries_admin_delete on public.timesheet_entries
for delete using (public.is_admin());

drop policy if exists heater_use_entries_member_read on public.heater_use_entries;
create policy heater_use_entries_member_read on public.heater_use_entries
for select using (
  public.can_read_heater_use_entry(id, responsible_member_id)
  or public.is_admin()
);

drop policy if exists heater_use_entries_member_insert on public.heater_use_entries;
create policy heater_use_entries_member_insert on public.heater_use_entries
for insert with check (
  public.is_admin()
  or (
    group_pay = false
    and responsible_member_id = public.current_account_member_id()
    and public.member_can_use_heater(responsible_member_id)
  )
);

drop policy if exists heater_use_entries_member_update on public.heater_use_entries;
create policy heater_use_entries_member_update on public.heater_use_entries
for update using (
  responsible_member_id = public.current_account_member_id()
  or public.is_admin()
);

drop policy if exists heater_use_entries_admin_delete on public.heater_use_entries;
create policy heater_use_entries_admin_delete on public.heater_use_entries
for delete using (public.is_admin());

drop policy if exists heater_use_group_members_member_read on public.heater_use_group_members;
create policy heater_use_group_members_member_read on public.heater_use_group_members
for select using (
  public.can_read_heater_group_member(heater_use_entry_id, account_member_id)
  or public.is_admin()
);

drop policy if exists heater_use_group_members_admin_write on public.heater_use_group_members;
create policy heater_use_group_members_admin_write on public.heater_use_group_members
for all using (public.is_admin())
with check (public.is_admin());

drop policy if exists admin_alerts_admin_only on public.admin_alerts;
create policy admin_alerts_admin_only on public.admin_alerts
for all using (public.is_admin())
with check (public.is_admin());

drop policy if exists billing_line_items_member_read on public.billing_line_items;
create policy billing_line_items_member_read on public.billing_line_items
for select using (
  account_member_id = public.current_account_member_id()
  or exists (
    select 1
    from public.account_members charge_member
    join public.account_members current_member
      on current_member.account_id = charge_member.account_id
    where charge_member.id = billing_line_items.account_member_id
      and current_member.auth_user_id = auth.uid()
      and current_member.is_billing_owner = true
  )
  or public.is_admin()
);

drop policy if exists billing_line_items_admin_write on public.billing_line_items;
create policy billing_line_items_admin_write on public.billing_line_items
for all using (public.is_admin())
with check (public.is_admin());

drop policy if exists automation_jobs_admin_only on public.automation_jobs;
create policy automation_jobs_admin_only on public.automation_jobs
for all using (public.is_admin())
with check (public.is_admin());

-- ---------------------------------------------------------------------------
-- Current Memberships import bridge
-- ---------------------------------------------------------------------------
-- `current_memberships` remains the raw AppSheet/Sheets import table.
-- The app reads/writes the normalized tables above because:
-- - account-level data is shared by account_number
-- - member-level data belongs to one person
-- - billing/credentials need tighter access than the raw import table

alter table public.account_members
  add column if not exists legacy_account_type text;

create or replace function public.jsonb_first_text(source jsonb, variadic keys text[])
returns text
language plpgsql
immutable
as $$
declare
  key text;
  value text;
begin
  foreach key in array keys loop
    if source ? key then
      value := nullif(btrim(source ->> key), '');
      if value is not null then
        return value;
      end if;
    end if;
  end loop;

  return null;
end;
$$;

create or replace function public.try_parse_int(raw_value text)
returns integer
language plpgsql
immutable
as $$
begin
  if raw_value is null or btrim(raw_value) = '' then
    return null;
  end if;

  return btrim(raw_value)::integer;
exception
  when others then
    return null;
end;
$$;

create or replace function public.try_parse_date(raw_value text)
returns date
language plpgsql
immutable
as $$
begin
  if raw_value is null or btrim(raw_value) = '' then
    return null;
  end if;

  begin
    return btrim(raw_value)::date;
  exception
    when others then
      begin
        return to_date(btrim(raw_value), 'MM/DD/YYYY');
      exception
        when others then
          return null;
      end;
  end;
end;
$$;

create or replace function public.try_parse_timestamptz(raw_value text)
returns timestamptz
language plpgsql
immutable
as $$
begin
  if raw_value is null or btrim(raw_value) = '' then
    return null;
  end if;

  return btrim(raw_value)::timestamptz;
exception
  when others then
    return null;
end;
$$;

create or replace function public.try_parse_bool(raw_value text)
returns boolean
language plpgsql
immutable
as $$
declare
  cleaned text;
begin
  if raw_value is null or btrim(raw_value) = '' then
    return null;
  end if;

  cleaned := lower(btrim(raw_value));

  if cleaned in ('yes', 'y', 'true', 't', '1', 'on') then
    return true;
  elsif cleaned in ('no', 'n', 'false', 'f', '0', 'off') then
    return false;
  end if;

  return null;
end;
$$;

create or replace function public.normalize_membership_account_type(raw_value text)
returns public.membership_account_type
language plpgsql
immutable
as $$
declare
  cleaned text;
begin
  cleaned := lower(regexp_replace(coalesce(raw_value, ''), '\s+', ' ', 'g'));
  cleaned := btrim(cleaned);

  if cleaned = '' then
    return 'Active Membership';
  elsif cleaned in ('active membership', 'active membership ') then
    return 'Active Membership';
  elsif cleaned in ('open gym only', 'open gym sign up', 'open gym signup') then
    return 'Open Gym Only';
  elsif cleaned = 'billed monthly' then
    return 'Billed Monthly';
  elsif cleaned = 'account manager' then
    return 'Account Manager';
  elsif cleaned in (
    'account past due no access allowed',
    'past due balance no access allowed',
    'waiting on contract & payment',
    'waiting on contract and payment',
    'waiting on contract',
    'subscriber account'
  ) or cleaned like '%past due%' or cleaned like '%no access%' then
    return 'Account Past Due NO ACCESS ALLOWED';
  elsif cleaned = 'new member' then
    return 'Active Membership';
  end if;

  return 'Active Membership';
end;
$$;

create or replace function public.normalize_account_billing_status(raw_value text)
returns public.account_billing_status
language plpgsql
immutable
as $$
declare
  cleaned text;
begin
  cleaned := lower(btrim(coalesce(raw_value, '')));

  if cleaned in ('incomplete', 'trialing', 'active', 'past_due', 'canceled', 'unpaid', 'paused') then
    return cleaned::public.account_billing_status;
  elsif cleaned in ('past due', 'past-due') then
    return 'past_due';
  elsif cleaned in ('cancelled', 'cancelled subscription') then
    return 'canceled';
  end if;

  return 'none';
end;
$$;

create or replace function public.sync_current_memberships_to_app_tables()
returns table (
  synced_accounts integer,
  synced_members integer,
  synced_billing_accounts integer,
  synced_credentials integer,
  skipped_rows integer
)
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
  if to_regclass('public.current_memberships') is null then
    raise exception 'public.current_memberships does not exist. Import the current membership sheet first, then rerun this function.';
  end if;

  create temp table if not exists tmp_current_memberships_norm (
    row_data jsonb,
    legacy_source_row_number integer,
    member_name text,
    account_type_text text,
    normalized_account_type public.membership_account_type,
    account_number text,
    membership_details text,
    notes_on_account text,
    expiration_date date,
    billing_id_heater text,
    marks_against_account text,
    phone_number text,
    email_address citext,
    image_path text,
    password_pin text,
    stripe_customer_id text,
    stripe_subscription_id text,
    stripe_status text,
    billing_status public.account_billing_status,
    current_period_end timestamptz,
    last_sync timestamptz,
    allow_guest_entry boolean,
    is_billing_owner boolean default false
  ) on commit drop;

  truncate table tmp_current_memberships_norm;

  execute $sql$
    insert into tmp_current_memberships_norm (
      row_data,
      legacy_source_row_number,
      member_name,
      account_type_text,
      normalized_account_type,
      account_number,
      membership_details,
      notes_on_account,
      expiration_date,
      billing_id_heater,
      marks_against_account,
      phone_number,
      email_address,
      image_path,
      password_pin,
      stripe_customer_id,
      stripe_subscription_id,
      stripe_status,
      billing_status,
      current_period_end,
      last_sync,
      allow_guest_entry
    )
    select
      source.row_data,
      public.try_parse_int(public.jsonb_first_text(source.row_data, 'source_row_number', 'legacy_source_row_number', '_RowNumber', 'Row Number', 'row_number', 'row_num')),
      public.jsonb_first_text(source.row_data, 'member_name', 'Member Name', 'MemberName', 'name', 'Name'),
      public.jsonb_first_text(source.row_data, 'account_type', 'Account Type', 'Public Account Type', 'public_account_type'),
      public.normalize_membership_account_type(public.jsonb_first_text(source.row_data, 'account_type', 'Account Type', 'Public Account Type', 'public_account_type')),
      public.jsonb_first_text(source.row_data, 'account_number', 'Account Number', 'AccountNumber'),
      public.jsonb_first_text(source.row_data, 'membership_details', 'membership_details_card', 'Membership Details Card', 'Membership Details Cards should only be used during the following times', 'Membership Details Cards'),
      public.jsonb_first_text(source.row_data, 'notes_on_account', 'Notes On Account', 'Notes'),
      public.try_parse_date(public.jsonb_first_text(source.row_data, 'expiration_date', 'Expiration Date')),
      public.jsonb_first_text(source.row_data, 'billing_id_heater', 'Billing ID Heater', 'BillingIDHeater'),
      public.jsonb_first_text(source.row_data, 'marks_against_account', 'Marks Against Account'),
      public.jsonb_first_text(source.row_data, 'phone_number', 'Phone Number', 'Phone'),
      nullif(public.jsonb_first_text(source.row_data, 'email_address', 'Email Address', 'Email'), '')::citext,
      public.jsonb_first_text(source.row_data, 'image_path', 'Image', 'image'),
      public.jsonb_first_text(source.row_data, 'legacy_password', 'password', 'Password', 'PIN', 'Pin'),
      public.jsonb_first_text(source.row_data, 'stripe_customer_id', 'StripeCustomerID', 'Stripe Customer ID'),
      public.jsonb_first_text(source.row_data, 'stripe_subscription_id', 'StripeSubscriptionID', 'Stripe Subscription ID'),
      public.jsonb_first_text(source.row_data, 'stripe_status', 'StripeStatus', 'Stripe Status'),
      public.normalize_account_billing_status(public.jsonb_first_text(source.row_data, 'billing_status', 'StripeStatus', 'Stripe Status', 'stripe_status')),
      public.try_parse_timestamptz(public.jsonb_first_text(source.row_data, 'current_period_end', 'CurrentPeriodEnd', 'Current Period End')),
      public.try_parse_timestamptz(public.jsonb_first_text(source.row_data, 'last_sync', 'LastSync', 'Last Sync')),
      public.try_parse_bool(public.jsonb_first_text(
        source.row_data,
        'allow_guest_entry',
        'Allow Guest Entry',
        'Allow guest entry and automatic billing at $0.25 a person.',
        'Allow Guest Entry And Automatic Billing At $0.25 A Person.'
      ))
    from (
      select to_jsonb(cm) as row_data
      from public.current_memberships cm
    ) source
  $sql$;

  delete from tmp_current_memberships_norm
  where member_name is null
     or account_number is null;

  get diagnostics skipped_rows = row_count;

  update tmp_current_memberships_norm
  set allow_guest_entry = coalesce(
    allow_guest_entry,
    normalized_account_type = 'Account Manager'
    or (
      normalized_account_type = 'Active Membership'
      and (
        stripe_customer_id is not null
        or stripe_subscription_id is not null
        or billing_status in ('active', 'trialing')
      )
    )
  );

  update tmp_current_memberships_norm norm
  set is_billing_owner = ranked.rn = 1
  from (
    select
      ctid,
      row_number() over (
        partition by account_number
        order by
          (stripe_customer_id is not null) desc,
          (stripe_subscription_id is not null) desc,
          (email_address is not null) desc,
          coalesce(legacy_source_row_number, 2147483647),
          member_name
      ) as rn
    from tmp_current_memberships_norm
  ) ranked
  where norm.ctid = ranked.ctid;

  insert into public.accounts (
    account_number,
    membership_details,
    notes_on_account,
    expiration_date,
    billing_id_heater,
    marks_against_account
  )
  select distinct on (account_number)
    account_number,
    membership_details,
    notes_on_account,
    expiration_date,
    billing_id_heater,
    marks_against_account
  from tmp_current_memberships_norm
  order by
    account_number,
    (membership_details is null),
    (notes_on_account is null),
    coalesce(legacy_source_row_number, 2147483647),
    member_name
  on conflict (account_number) do update set
    membership_details = coalesce(excluded.membership_details, public.accounts.membership_details),
    notes_on_account = coalesce(excluded.notes_on_account, public.accounts.notes_on_account),
    expiration_date = coalesce(excluded.expiration_date, public.accounts.expiration_date),
    billing_id_heater = coalesce(excluded.billing_id_heater, public.accounts.billing_id_heater),
    marks_against_account = coalesce(excluded.marks_against_account, public.accounts.marks_against_account),
    updated_at = now();

  get diagnostics synced_accounts = row_count;

  update public.account_members am
  set is_billing_owner = false,
      updated_at = now()
  from public.accounts a
  where am.account_id = a.id
    and a.account_number in (
      select distinct account_number
      from tmp_current_memberships_norm
    );

  insert into public.account_members (
    account_id,
    member_name,
    account_type,
    phone_number,
    email_address,
    image_path,
    allow_guest_entry,
    is_billing_owner,
    legacy_source_row_number,
    legacy_member_name,
    legacy_account_type
  )
  select
    a.id,
    norm.member_name,
    norm.normalized_account_type,
    norm.phone_number,
    norm.email_address,
    norm.image_path,
    norm.allow_guest_entry,
    norm.is_billing_owner,
    norm.legacy_source_row_number,
    norm.member_name,
    norm.account_type_text
  from tmp_current_memberships_norm norm
  join public.accounts a
    on a.account_number = norm.account_number
  on conflict (account_id, member_name) do update set
    account_type = excluded.account_type,
    phone_number = excluded.phone_number,
    email_address = excluded.email_address,
    image_path = excluded.image_path,
    allow_guest_entry = excluded.allow_guest_entry,
    is_billing_owner = excluded.is_billing_owner,
    legacy_source_row_number = coalesce(excluded.legacy_source_row_number, public.account_members.legacy_source_row_number),
    legacy_member_name = excluded.legacy_member_name,
    legacy_account_type = excluded.legacy_account_type,
    updated_at = now();

  get diagnostics synced_members = row_count;

  insert into public.account_billing (
    account_id,
    stripe_customer_id,
    stripe_subscription_id,
    stripe_status,
    billing_status,
    current_period_end,
    last_sync
  )
  select
    a.id,
    billing.stripe_customer_id,
    billing.stripe_subscription_id,
    billing.stripe_status,
    billing.billing_status,
    billing.current_period_end,
    billing.last_sync
  from (
    select distinct on (account_number)
      account_number,
      stripe_customer_id,
      stripe_subscription_id,
      stripe_status,
      billing_status,
      current_period_end,
      last_sync
    from tmp_current_memberships_norm
    order by
      account_number,
      (stripe_customer_id is not null) desc,
      (stripe_subscription_id is not null) desc,
      coalesce(legacy_source_row_number, 2147483647)
  ) billing
  join public.accounts a
    on a.account_number = billing.account_number
  on conflict (account_id) do update set
    stripe_customer_id = coalesce(excluded.stripe_customer_id, public.account_billing.stripe_customer_id),
    stripe_subscription_id = coalesce(excluded.stripe_subscription_id, public.account_billing.stripe_subscription_id),
    stripe_status = coalesce(excluded.stripe_status, public.account_billing.stripe_status),
    billing_status = excluded.billing_status,
    current_period_end = coalesce(excluded.current_period_end, public.account_billing.current_period_end),
    last_sync = coalesce(excluded.last_sync, public.account_billing.last_sync),
    updated_at = now();

  get diagnostics synced_billing_accounts = row_count;

  insert into public.member_credentials (
    account_member_id,
    pin_hash,
    must_reset_pin
  )
  select
    am.id,
    crypt(norm.password_pin, gen_salt('bf')),
    false
  from tmp_current_memberships_norm norm
  join public.accounts a
    on a.account_number = norm.account_number
  join public.account_members am
    on am.account_id = a.id
   and am.member_name = norm.member_name
  where norm.password_pin is not null
  on conflict (account_member_id) do update set
    pin_hash = excluded.pin_hash,
    must_reset_pin = false,
    updated_at = now();

  get diagnostics synced_credentials = row_count;

  return next;
end;
$$;

create or replace view public.account_member_profiles
with (security_invoker = true) as
select
  am.id as account_member_id,
  am.account_id,
  a.account_number,
  am.member_name,
  am.account_type,
  am.legacy_account_type,
  am.phone_number,
  am.email_address,
  am.image_path,
  am.allow_guest_entry,
  am.is_billing_owner,
  a.membership_details,
  a.notes_on_account,
  a.expiration_date,
  a.billing_id_heater,
  a.marks_against_account,
  ab.stripe_status,
  ab.billing_status,
  ab.current_period_end,
  ab.last_sync,
  am.created_at,
  am.updated_at
from public.account_members am
join public.accounts a
  on a.id = am.account_id
left join public.account_billing ab
  on ab.account_id = a.id;

do $$
begin
  if to_regclass('public.current_memberships') is not null then
    perform *
    from public.sync_current_memberships_to_app_tables();
  end if;
end $$;
